### ISSUE TITLE
Citation problem for multiple authors, listing all authors instead of writing et al.

### ISSUE THREAD

**Issue by aysegulozkaya** [michel-kraemer/citeproc-java#107]
I have a problem with multiple authors. I expect if the article has more than 10 authors (Can I set this value 7, 10, or another value?), it will write first author + et. al.  For example: "Measurement of quark- and gluon-like jet fractions using jet charge in PbPb and pp collisions at 5.02 TeV" the article citation in IEEE format works correctly as shown below.

A. M. Sirunyan et al., “Measurement of quark- and gluon-like jet fractions using jet charge in PbPb and pp collisions at 5.02 TeV,” JOURNAL OF HIGH ENERGY PHYSICS, no. 7, pp. 0–0, 2020, Accessed: 00, 2020. [Online]. 

But other formats like ACM, APA, CHICAGO, MLA, BibTeX writes all of the authors. For example ACM output: 

A. M. Sirunyan, A. Tumasyan, W. Adam, F. Ambrogi, E. Asilar, T. Bergauer, J. Brandstetter, M. Dragicevic, J. Eroe, and A. Escalante Del Valle. 2020. Measurement of quark- and gluon-like jet fractions using jet charge in PbPb and pp collisions at 5.02 TeV. JOURNAL OF HIGH ENERGY PHYSICS 7 (2020)

(There are a lot of authors, I just show 10 authors)

I use citeproc java 3.0.0-alpha.1 and 21.4 snapshots for styles.

Thank you for your help.
Aysegul

**Comment by michel-kraemer** [comment]
Yes, this is a known issue in citeproc-java 3.0.0-alpha.1. I've just released 3.0.0-alpha.2 this morning. Can you please try again with this version?

**Comment by aysegulozkaya** [comment]
Thank you for your immediate response. The new version works for IEEE, APA, CHICAGO, MLA, and BibTeX, but the problem still occurs for the ACM style. Also, the etAlMin is different for all styles. Can I set the same number for all styles (The styles I used)?

**Comment by michel-kraemer** [comment]
This issue seems to be fixed in the latest citeproc-java version.
