### ISSUE TITLE
EcmaError TypeError when the bibliography is making

### ISSUE THREAD

**Issue by acheype** [michel-kraemer/citeproc-java#26]
I've tried a lot of different ways to compute a bibliography as I observed in the unit test file : [CSLTest.java](https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/src/test/java/de/undercouch/citeproc/CSLTest.java), but the same exception is always raised.

This is an example :
```
        CSLItemData item =new CSLItemDataBuilder()
            .id("Lycklama:1978:UTSb")
            .type(CSLType.ARTICLE_JOURNAL)
            .title("UNIX Time-Sharing System: UNIX on a Microprocessor")
            .author("H.", "Lycklama")
            .volume(57)
            .issue(6)
            .page("2087-2101")
            .issued(new CSLDateBuilder().dateParts(new int[]{1978, 7}, new int[]{1978, 8}).build())
            .containerTitle("The Bell System Technical Journal")
            .ISSN("0005-8580")
            .URL("http://bstj.bell-labs.com/BSTJ/images/Vol57/bstj57-6-2087.pdf")
            .build();

        try {
            CSL citeproc = new CSL(new ListItemDataProvider(item), "/config/citeproc/ieee.csl");
            List<Citation> a = citeproc.makeCitation(item.getId());
            citeproc.setOutputFormat("text");
            Bibliography b = citeproc.makeBibliography();
            return b.getEntries()[0];
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
```

And each time I get these exceptions :
```
java.lang.IllegalArgumentException: Could not make bibliography
	at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:444)
	at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:412)
	at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:398)
...
Caused by: de.undercouch.citeproc.script.ScriptRunnerException: Could not execute code
	at de.undercouch.citeproc.script.RhinoScriptRunner.eval(RhinoScriptRunner.java:119)
	at de.undercouch.citeproc.CSL.makeBibliography(CSL.java:432)
	... 140 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: Impossible de lire la propriété "strings" de undefined (<code>#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981)
...
```
(translation of the last one : Impossible to read the "strings" property of undefined)

I've noted the the CSL file is well read.
Also I've declared in my pom.xml, the followed versions :
* Rhino : 1.7.7
* Citeproc-java : 0.6

Could you help me please ??

Cheers,
Adrien

**Comment by michel-kraemer** [comment]
Can you please try it again with 1.0.0-SNAPSHOT?

https://oss.sonatype.org/content/repositories/snapshots/de/undercouch/citeproc-java/1.0.0-SNAPSHOT/

This should solve the problem.

**Comment by acheype** [comment]
Thanks for your quick answer.

The 1.0.0-SNAPSHOT didn't solve my problem... But the real problem was I didn't have any citation-style locale installed !
So as explained in the [download](http://michel-kraemer.github.io/citeproc-java/download/) page of your website, I declared the artefacts org.citationstyles.styles and org.citationstyles.locales in my pom.xlm. And it works !

Just two questions :
* For a better stability, which version do you advise me : the 1.0.0-SNAPSHOT (ever it's a snapshot !) or the 0.6 ?
* Is there any way to declare that I don't want the reference part ([1], [2]...) in any citation ?

Thanks

**Comment by michel-kraemer** [comment]
> For a better stability, which version do you advise me : the 1.0.0-SNAPSHOT (ever it's a snapshot !) or the 0.6 ?

I suggest 1.0.0-SNAPSHOT. It's quite stable and I'm going to release 1.0.0 soon.

> Is there any way to declare that I don't want the reference part ([1], [2]...) in any citation ?

This totally depends on the style chosen. There is an online CSL style editor allowing you to create your own style if you need to.

Cheers,
Michel

**Comment by acheype** [comment]
Thanks, this I'm staying with  the 1.0.0-SNAPSHOT.

You're right for the CSL style. I don't have that type of reference with the style I need : the APA one.

Best regards,
Adrien
